### ISSUE TITLE
Enhance indexer to include full text of content

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight-dor-resources#2]

**Comment by peetucket** [comment]
From Ben, other collections: 

Jarndyce Collection (has xml & pdf at page level, object-level pdf): https://argo.stanford.edu/view?f%5Btag_facet%5D%5B%5D=Project+%3A+Jarndyce+Single-Volume+Nineteenth-Century+Novel+Collection

GATT Official Docs (page-level txt, object-level pdf): https://argo.stanford.edu/view?f%5Bcollection_title_facet%5D%5B%5D=GATT+Official+Documents

Archive Parlementaires (page-level txt, object-level pdf & xml): https://argo.stanford.edu/view?f%5Bapo_title_facet%5D%5B%5D=Archives+parlementaires

**Comment by peetucket** [comment]
See this ticket for more research: https://jirasul.stanford.edu/jira/browse/METADOR-73
