### ISSUE TITLE
spotlight indexing not working?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/spotlight-dor-resources#20]
Most recent indexing of feigenbaum (from the button on the UI) had these problems:

- [x] it halted with no explanation
- [x] logging is too verbose (sul-dlss/gdor-indexer#62)
- [x] logging doesn't indicate when a record has been successfully indexed. (#31)

**Comment by ndushay** [comment]
actual record indexing is done by solrizer; would need to log message directly after successful add.

**Comment by ndushay** [comment]
addressed too verbose logging with changes to gdor-indexer that set the default logging level to INFO and allow log_level to be set in config yml file.

**Comment by ndushay** [comment]
End of indexing stats logging:  
* https://github.com/sul-dlss/gdor-indexer/blob/master/lib/gdor/indexer.rb#L260-L271
* https://github.com/sul-dlss/gdor-indexer/blob/master/lib/gdor/indexer.rb#L237-L258

Individual record indexing logging:
* https://github.com/sul-dlss/harvestdor-indexer/blob/master/lib/harvestdor/indexer/solr.rb#L23-L36

**Comment by ndushay** [comment]
461 private objects
16876  according to argo  (all items)

**Comment by peetucket** [comment]
By Argo's count we should have 16,415 items (public).  On November 4, we indexed 16,415 (wow, cool).  On November 5, we index 16,241 (174 less).

**Comment by ndushay** [comment]
@cbeer  with the improved logging, do we now know for certain if we are indexing all the records we should be, and dropping none?  Do we know that we are getting logging when indexing fails?

**Comment by cbeer** [comment]
That's the hope. We haven't tried it out yet, though.
