### ISSUE TITLE
Indexing two new fields, splitting collector out of names

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/spotlight-dor-resources#36]
Currently the author/contributor solr field gets any names listed in MODs, including collector.  For spotlight exhibits, Tom has requested that we do not do this.  I suggest we keep the current SW based author/contributor field as is, but add two new fields for spotlight exhibits:

* all names, EXCEPT collector
* only collector

The exhibit curator can then decide which of these three facets to show (presumably not all three, and in the case of Feigbenbaum, it will be the one that excludes the contributor)

**Comment by cbeer** [comment]
Do we have any example records where we're indexing the collector name?

**Comment by peetucket** [comment]
Some examples of Feibenbaum listed as the author in Spotlight, but having different roles in MODs, and where they should end up:

Field 1: (creator/contributor?)
xk116vc5082: shows Feigbenbaum as creator only
gb989ss5949: shows Buchanan as creator and Feigbenbaum as contributor

Field 2: (collector)
vm902rb6648,gt415wd5479: shows Feigbenbaum as collector only

**Comment by cbeer** [comment]
When you say "contributor" above, should some of those read "collector"?

**Comment by peetucket** [comment]
@cbeer yes sorry for the confusion, i edited the topline description
