### ISSUE TITLE
Index the <note> field so it can be shown in exhibits

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/spotlight-dor-resources#51]
The generic <note> field may have valuble content, and does for Feigbenbaum.  This field needs to be searchable and displayed on item details page.

For example, https://purl.stanford.edu/vx023pr3537.mods

- [ ] update spotlight-dor-resources to index the field - as a tokenized text field, not a single token facet field
- [ ] update sul_exhibits_template to have the new field available for display (NOT a facet)

**Comment by peetucket** [comment]
Also need to add the new field to sul_exhibits_template when indexed and available.

**Comment by ndushay** [comment]
@peetucket   the content in all ```<note>``` fields is already searched via the catch-all field for an All Fields/Everything search.  The only reason to make the new field searchable is to allow it to be boosted differently (!) OR to allow a pulldown sort of search on it (!).   

In fact, the only reason to make the new field at all is for display purposes.

**Comment by ndushay** [comment]
(I can't figure out the query to get all documents in the profiler that have a note field without type or displayLabel attributes)

**Comment by peetucket** [comment]
According the spreadsheet and the MODs template, it should be all documents for Feigbenbaum (have a <note> with no attribute)
