### ISSUE TITLE
Feigenbaum: Index the document sub-type into a new field

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/spotlight-dor-resources#52]
This is exactly analogous to the donor tags for Feigenbaum.  

Useful for Feigenbaum only for now, but according to Shelley, could apply to other collections as well.

```xml
<mods>
  <note displayLabel="Document subtype">blah</note>
</mods>
```
needs to go into a new facet entitled  "Document subtype"

- [ ] update spotlight-dor-resources  to index the field
- [ ] update sul_exhibits_template to add the new field to the facets in catalog_controller

example record:  https://purl.stanford.edu/jr341rp6514.mods

```xml
<mods>
  <note displayLabel="Document subtype">presentations (communicative events)</note>
</mods>
```

**Comment by ndushay** [comment]
This is exactly analogous to the donor tags field:

```xml
<mods>
  <note displayLabel="Document subtype">presentations (communicative events)</note>
</mods>
```

entire universe of ​*profiled*​ mods objects (a small, bizarre subset of our DOR objects) has these displayLabel values for note fields:

https://sul-solr-a.stanford.edu/solr/mods_profiler/select?rows=0&facet.field=note_displayLabel_sim

(note:  sul-solr-a b/c mods_profiler is not on sul-solr-c and so does not always appear at sul-solr (plain) if the leader is c or some such)

currently:
```xml
<lst name="note_displayLabel_sim">
  <int name="Document subtype">3663</int>  # all feigenbaum -- see below
  <int name="Donor tags">2830</int>  # all feigenbaum -- see below
  <int name="statement of responsibility">919</int>
  <int name="state_note">515</int>
  <int name="general_state_note">496</int>
  <int name="Contact">414</int>
  <int name="Preferred Citation">413</int>
  <int name="Related Publication">410</int>
  <int name="state_node_4">292</int>
  <int name="state_node_1">263</int>
  <int name="location_code">184</int>
  <int name="state_node_5">178</int>
  <int name="citation/reference">135</int>
  <int name="general note">135</int>
  <int name="state_node_6">109</int>
  <int name="state_node_7">74</int>
  <int name="state_node_8">56</int>
  <int name="Preferred citation">53</int>
  <int name="Supplemental information">53</int>
  <int name="Conceptual consistency report">41</int>
  <int name="Attribute accuracy report">40</int>
  <int>71487</int>   # there is no displayLabel attrib
</lst>
```

For feigenbaum only:

https://sul-solr-a.stanford.edu/solr/mods_profiler/select?rows=0&facet.field=note_displayLabel_sim&fq=collection:feigenbaum

```xml
<lst name="note_displayLabel_sim">
  <int name="Document subtype">3663</int>
  <int name="Donor tags">2830</int>
  <int name="Reformatting note">14</int>
  <int>11100</int>  # there is no displayLabel attrib
</lst>
```
