### ISSUE TITLE
Simplify DorResource class based on changes to Spotlight

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/spotlight-dor-resources#6]
See https://github.com/sul-dlss/spotlight/pull/1202#issuecomment-149424315

**Comment by ndushay** [comment]
Chris thinks: "this should simplify Spotlight::Resources::DorResource down to something like:

```ruby
module Spotlight::Resources
  class DorResource < Spotlight::Resource
    def to_solr
      return to_enum :to_solr unless block_given?
      
      base_doc = super
      
      [resource, (resource.items if resource.collection?)].flatten.compact.each do |res|
        yield base_doc.merge(Spotlight::Dor::Resources.indexer.solr_document(res))
      end
    end
    
    private
    
    def resource
      @resource ||= Spotlight::Dor::Resources.indexer.resource doc_id
    end
  end
end
```

**Comment by peetucket** [comment]
0a00e69a71847bcd86e6af39abab606b2244d0a2 has the simplification applied, but had to make the resource method *not* private.  There is a spec for "reindex" that now fails - that method was removed and the test is trying to write a doc to jetty, failing in the process.  Its not clear to me if this failure is benign or the true problem.
